module(
    name = "crashpad",
    version = "0.8.0",
    bazel_compatibility = [">=7.2.1"],  # for `overlay/` directory
)

bazel_dep(name = "apple_support", version = "2.5.4")
bazel_dep(name = "rules_cc", version = "0.2.18")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "bazel_features", version = "1.47.1")
bazel_dep(name = "zlib", version = "1.3.2")
bazel_dep(name = "mini_chromium", version = "0.0.0-706fce5b.1")
single_version_override(
    module_name = "mini_chromium",
    patch_strip = 1,
    patches = ["patches/0002-mini-chromium-add-coregraphics-coretext-frameworks.patch"],
)

bazel_dep(name = "googletest", version = "1.17.0.bcr.2")
bazel_dep(name = "boringssl", version = "0.20260508.0")

# Force `libpfm` dependency to be `4.13.0`. This is required by `google_benchmark` for `boringssl`.
bazel_dep(name = "libpfm", version = "4.13.0")

lss = use_extension("//third_party/lss:extension.bzl", "lss")
use_repo(lss, "lss")

macos_sdk = use_repo_rule("//build/mig:sdk.bzl", "mig_macos_sdk")

macos_sdk(name = "mig_macos_sdk")
